[package]
name = "bloomberg-preinterview"
version = "1.0.0"
edition = "2021"

[lib]
name = "libbloom22"
path = "src/lib.rs"

[[bin]]
name = "bin_test"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
